# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  com:
    axonivy:
      connector:
        sproof:
          # Sproof API Token
          #[password]
          apiToken: ${decrypt:}
          # Email address of sender
          senderEmail: ""
          # First name of sender
          senderFirstname: ""
          # Last name of sender
          senderLastname: ""
